# Generated by Django 6.0.3 on 2026-03-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_city_city_name_en_city_city_name_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_name_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_name_ky',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_name_ru',
        ),
        migrations.RemoveField(
            model_name='district',
            name='district_name_en',
        ),
        migrations.RemoveField(
            model_name='district',
            name='district_name_ky',
        ),
        migrations.RemoveField(
            model_name='district',
            name='district_name_ru',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_name_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_name_ky',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_name_ru',
        ),
    ]
