# Generated by Django 6.0.3 on 2026-04-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0004_remove_city_city_name_en_remove_city_city_name_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='room',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('свободная планировка', 'свободная планировка')], max_length=56),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='house_app.property'),
        ),
    ]
