# Generated by Django 6.0.3 on 2026-04-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0005_alter_property_room_alter_propertyimage_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='property',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='property_review', to='house_app.property'),
            preserve_default=False,
        ),
    ]
