# Generated by Django 6.0.3 on 2026-04-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0006_review_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='buyer',
        ),
    ]
